#This message describes the id and state of a car (x,y,theta,v) 
#A fifth variable not present here, desiredV, describes the speed at which
#the vehicle desires to travel in the highway. It is
# necessary for the platoon dynamics studied in the Sim_Highway simulator.
# It is set by each vehicle.
# http://github.com/federicomassa/Sim_Highway.git
uint8 id 
float64 x
float64 y
float64 theta
float64 v